[e1]
name = "Nivedita"
institution = "University of Oxford"
date = 2024-11-06
[e2]
name = "Yang-Hui He"
institution = "University of Oxford; City, University of London"
date = 2024-11-13
title = "The AI Mathematician: From Physics, to Geometry, to Number Theory"
abstract = "We summarize how AI can approach mathematics in three ways: theorem-proving, conjecture formulation, and language processing. Inspired by initial experiments in geometry and string theory, we present a number of recent experiments on how various standard machine‐learning algorithms can help with pattern detection across disciplines ranging from algebraic geometry to representation theory, to combinatorics, and to number theory. At the heart of the programme is the question: how does AI help with mathematical discovery?"

[e3]
name = "Kymani Tieral Keden Armstrong‐Williams"
institution = "Queen Mary University of London"
date = 2024-09-25

[e4]
name = "Martina Bártová and Samuel Valach"
institution = "Coláiste na Tríonóide, Baile Átha Cliath"
date = 2024-10-02

[e5]
name = "Sonja Klitsch"
institution = "Oilthigh Dhùn Èideann"
date = 2024-10-09

[e6]
name = "Mario García-Fernández"
institution = "Instituto de Ciencias Matemáticas, Universidad Autónoma de Madrid"
date = 2024-10-30

